title: Brayan's Blog
description: AI/ML Research, Engineering
theme: minima
author:
  name: Brayan

minima:
  skin: classic
  social_links:
    github: Brayanbrayan

markdown: kramdown
kramdown:
  math_engine: null
  input: GFM
  syntax_highlighter: rouge
